### ISSUE TITLE
Another Issue With Compiling

### ISSUE THREAD

**Issue by Bacon69000** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#39]
### Describe your problem here.

Hi again, so i was just building the game normally when suddenly this error popped up:

![image](https://user-images.githubusercontent.com/97658439/170246217-111c218f-b75b-45d9-84a0-52d08f7ddd5f.png)

If you know anything about the error, let me know in the comments!.

Thanks for your attention.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by Randomxdp** [comment]
too new jdk

**Comment by Randomxdp** [comment]
try installing java 8 instead

**Comment by Bacon69000** [comment]
> try installing java 8 instead

i have java 8 and jdk 17

**Comment by jigsaw-4277821** [comment]
You need to use only jdk 8

**Comment by TomyGamy** [comment]
hello, I have the same problem, and I have Java and JDK 8

**Comment by TomyGamy** [comment]
> hello, I have the same problem, and I have Java and JDK 8

Oh yeah, I forgot lime setup android
