### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by Ouzo4** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#40]
### Describe your problem here.

Error: In file included from include/llua/Lua_helper.h:10:0, from ./src/__boot__.cpp:787:
C:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/linc_lua.h:3:19: fatal error: E:/FNF-PsychEngine-Android/export/release/android/obj/obj/android-v7/__pch/haxe/hxcpp.h: No such file or directory
 #include <hxcpp.h>
compilation terminated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
If it shows this error at the of lime test android put `-D NO_PRECOMPILED_HEADERS`
