### ISSUE TITLE
Black screen after launching or crash

### ISSUE THREAD

**Issue by TomyGamy** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#45]
### Describe your bug here.

After installing and launching the game, it had a black screen with the error sound from fixel, but I cant go to the console.
![image](https://user-images.githubusercontent.com/95078425/171865129-f03ea765-8810-4d02-b056-09c0ac038047.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Impoted Android stuff in my engine

**Comment by jigsaw-4277821** [comment]
Why you ask me if you took the android codes to your engine?
