### ISSUE TITLE
Unstoppable Error Message

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#47]
### Describe your bug here.

Screenshot of what's going on but mostly I've reinstalled the app 2 times and it keeps giving me this :(
![Screenshot_20220605-015702](https://user-images.githubusercontent.com/59747809/172037497-6857d4d9-a821-4544-b264-2f9ebd1edde7.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base download from Actions Tab

**Comment by ImaginationSuperHero528** [comment]
1. No I can't seem to show more of the message cause of rotation lock.
2. Build Target doesn't have an Android option.

**Comment by jigsaw-4277821** [comment]
This happens because you didn't put all the assets correctly in the android storage (this error must appears because the notes XML is corrupted)
