### ISSUE TITLE
Unstoppable Custom Week Bug

### ISSUE THREAD

**Issue by BobOffnf** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#56]
### Describe your bug here.

So,Everytime I Try to Run A Mod With the Engine,The Engine Just Crashes,Idk Why :(
Footage:https://cdn.discordapp.com/attachments/932776084762656768/986056684352978984/mobizen_20220613_205104.mp4

### Command Prompt/Terminal logs (if existing)

/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.hx (line 318)
/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.hx (line 85)
/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 140)
FreeplayState.hx (line 60)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Invalid char 125 at position 273

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope I Didnt,I Just Made An Custom Week Without Changing Any Normal FNF Settings.

**Comment by jigsaw-4277821** [comment]
You corrupted the json

**Comment by mcagabe19** [comment]
corrupted json or your mistake
