### ISSUE TITLE
These are the functions that I can't use in Android version

### ISSUE THREAD

**Issue by AyderProgramic** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#59]
### What feature do you want to get added on the **base** engine?

Some mods have custom dialogs in which you need to press space to continue the dialog, make it so that during the dialog, pressing on an empty space is considered as space or enter, or you can do it as a separate button, also add a space during the rap battle  , in some mods it is used as an evasion! 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by jigsaw-4277821** [comment]
You can't add a space button in android
