### ISSUE TITLE
You must have a "project.xml" file or specify another valid project file when using the 'test' command

### ISSUE THREAD

**Issue by bgm145632** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#63]
### Describe your bug here.

There is "project.xml" in the directory. Why does this happen?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by jigsaw-4277821** [comment]
Yeap
