### ISSUE TITLE
Save in Chart Editor.

### ISSUE THREAD

**Issue by TwistChris** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#66]
### Describe your bug here.

I wanted to save a chart that I modify on the phone. But when I save, I don't have the chart.
That of Kvits, it is corrected this problem, but it did not update the engine. You can correct.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Non.

**Comment by jigsaw-4277821** [comment]
The file isn't saved in clipboard anymore, is saved where your assets and mods folder's are located

**Comment by jigsaw-4277821** [comment]
In saves folder

**Comment by TwistChris** [comment]
Ok, thank you
