### ISSUE TITLE
Section 0 in Chart Editor

### ISSUE THREAD

**Issue by TwistChris** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#68]
### Describe your bug here.

I wanted to see the chart I'm making in Chart Editor, and I go to Section 0 and the game crashes. I did not understand. So I go back to the game and I come to Section 0, I touch the left button after the right button, the game crashes. And it does that in all music. Everything was on the phone.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Non.

**Comment by mcagabe19** [comment]
(Everything was on the phone) bruh

**Comment by jigsaw-4277821** [comment]
That is an issue from psych itself
