### ISSUE TITLE
Delay Game Camera

### ISSUE THREAD

**Issue by PHG29** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#72]
### Describe your bug here.

For some reason, in the most recent builds, the game camera has a huge delay when changing its tracking position (like changing the focus on the chart) among others

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the latest build

**Comment by jigsaw-4277821** [comment]
..... This from psych engine itself not from me
