### ISSUE TITLE
Week 7 update 

### ISSUE THREAD

**Issue by FuzzMations** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#73]
### What feature do you want to get added on the **base** engine?

The officql psych engine week 7 update is out and was wondering if you can add it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by jigsaw-4277821** [comment]
🗿

**Comment by jigsaw-4277821** [comment]
Is already

**Comment by mcagabe19** [comment]
bruh
