### ISSUE TITLE
Game over

### ISSUE THREAD

**Issue by Sopademacaco1** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#76]
### Describe your bug here.

Game crash when You die

### Command Prompt/Terminal logs (if existing)

```bash
No log
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
Ur Phone bad

**Comment by Sopademacaco1** [comment]
![images (17)](https://user-images.githubusercontent.com/96175390/175611020-03a3bf66-9e85-46c6-88ce-15794a025d54.jpeg)
