### ISSUE TITLE
Bug Android bruh

### ISSUE THREAD

**Issue by Miguelpescript** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#83]
### Describe your bug here.

when i open the android app it automatically exits
yes i enabled all permissions

### Command Prompt/Terminal logs (if existing)

```bash
Idk
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Azeanimates31** [comment]
Same

**Comment by jigsaw-4277821** [comment]
Fixed
