### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Azeanimates31** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#84]
### Describe your bug here.

It crashes when you open the apk and no i don't have a weak phone 

### Command Prompt/Terminal logs (if existing)

```bash
H
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Azeanimates31** [comment]
I don't use Neko, HashLink, or other build system 
I just put that for nothing

**Comment by jigsaw-4277821** [comment]
Are you downloaded the latest build?

**Comment by Miguelpescript** [comment]
:)
STILL
NOT
WORKING
HAHAHAHAHA

**Comment by Sussysnowman** [comment]
Rip still crashes good luck fixing it :trollface:

**Comment by jigsaw-4277821** [comment]
Wait for the last one

**Comment by Sussysnowman** [comment]
Ok

**Comment by Sussysnowman** [comment]
Bruh it still crashes 🗿

**Comment by Sussysnowman** [comment]
Bruh moment 🗿

**Comment by Miguelpescript** [comment]
Good news for saw













is not working :)

**Comment by Sussysnowman** [comment]
Yes please fix it saw 😭

Lmfao💀

**Comment by Sussysnowman** [comment]
💀

**Comment by Miguelpescript** [comment]
he died




LOL

**Comment by Sussysnowman** [comment]
Yes lmfao💀

**Comment by Bissthefreak** [comment]
Lmao

**Comment by Sussysnowman** [comment]
Lmfao 💀

**Comment by jigsaw-4277821** [comment]
Now is working

**Comment by Motasembltaje** [comment]
I have problem, when I enter any song, the game crash
