### ISSUE TITLE
Can't hit notes 

### ISSUE THREAD

**Issue by MatiazAnims** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#86]
### Describe your bug here.

I can't hit notes, for some reason i can hit long notes but not normal ones, android 11, a22

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
Don't disable the controller mode from options
