### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by PHG29** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#89]
### Describe your bug here.

In the menu the A and B buttons do not work to open anything

### Command Prompt/Terminal logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the latest build

**Comment by BobOffnf** [comment]
tbh the only button that works on the menu is E

**Comment by jigsaw-4277821** [comment]
It should be fixed in the latest build now 😃
