### ISSUE TITLE
I can't load a song. Help 

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [jigsaw-4277821/FNF-PsychEngine-With-Android-Support#90]
### Describe your bug here.

Everytime I try to load a song I get an error that says ret = Function_Continue 

### Command Prompt/Terminal logs (if existing)

```bash
ret = Function_Continue
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
That was for testing, is removed now
